//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LkUgtu.orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Param_Resume
    {
        public int idParam_Resume { get; set; }
        public int idParam { get; set; }
        public int idResume { get; set; }
        public Nullable<int> idResumeZnachParam { get; set; }
        public Nullable<int> Chislo { get; set; }
        public string Stroka { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    
        public virtual Parametr Parametr { get; set; }
        public virtual Resume Resume { get; set; }
        public virtual ZnachParam ZnachParam { get; set; }
    }
}
