//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LkUgtu.orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public decimal nCode { get; set; }
        public string Clastname { get; set; }
        public string Cfirstname { get; set; }
        public string Cotch { get; set; }
        public Nullable<System.DateTime> Dd_birth { get; set; }
        public string Cplacebirth { get; set; }
        public Nullable<bool> Linval { get; set; }
        public Nullable<bool> Ldeti { get; set; }
        public Nullable<bool> Lrab { get; set; }
        public Nullable<bool> lSex { get; set; }
        public Nullable<bool> Lobchegit { get; set; }
        public string cSotTel { get; set; }
        public string ctelefon { get; set; }
        public string cEmail { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> Ik_grazd { get; set; }
        public Nullable<int> Ik_sem_pol { get; set; }
        public string cInn { get; set; }
        public string cStrax { get; set; }
        public Nullable<int> ik_voen_zvanie { get; set; }
        public Nullable<int> itab_n { get; set; }
        public Nullable<int> ik_nac { get; set; }
        public System.Guid PersonGUID { get; set; }
        public string PersonFullName { get; set; }
        public string PersonSmallName { get; set; }
        public string PersName { get; set; }
    }
}
