//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LkUgtu.orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predpriyatie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Predpriyatie()
        {
            this.Vakans = new HashSet<Vakans>();
            this.Trudoustr = new HashSet<Trudoustr>();
        }
    
        public int IDPredpriyatie { get; set; }
        public Nullable<int> IDShtat { get; set; }
        public Nullable<int> IDSfera { get; set; }
        public Nullable<int> IDAddress { get; set; }
        public string Name { get; set; }
        public string FIORuk { get; set; }
        public string DolznostRuk { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public string Faks { get; set; }
        public string KontaktLico { get; set; }
        public string DolznostKLico { get; set; }
        public string KontaktTelefon { get; set; }
        public string KontaktEmail { get; set; }
        public string KontaktFaks { get; set; }
        public string KontaktLicoTr { get; set; }
        public string DolznostKLicoTr { get; set; }
        public string KontaktTelefonTr { get; set; }
        public string KontaktEmailTr { get; set; }
        public string KontaktFaksTr { get; set; }
        public Nullable<int> IDDolznostRuk { get; set; }
        public Nullable<int> IDDolznostKLico { get; set; }
        public Nullable<int> IDDolznostKLicoTr { get; set; }
        public string WebSite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vakans> Vakans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trudoustr> Trudoustr { get; set; }
    }
}
