//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LkUgtu.orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trudoustr
    {
        public int IDTrudoustr { get; set; }
        public decimal IDStudent { get; set; }
        public Nullable<int> IDDolznost { get; set; }
        public Nullable<int> IDVidPraktiki { get; set; }
        public int IDPredpriyatie { get; set; }
        public Nullable<int> IDResume { get; set; }
        public Nullable<int> IDVakans { get; set; }
        public Nullable<bool> RabotaPoSpec { get; set; }
        public Nullable<bool> RabotaVRegion { get; set; }
        public Nullable<System.DateTime> DataObzvon { get; set; }
        public Nullable<System.DateTime> DataBegin { get; set; }
        public Nullable<System.DateTime> DataEnd { get; set; }
        public Nullable<bool> Spravka { get; set; }
        public Nullable<int> ZarPlata { get; set; }
        public Nullable<int> IDFile { get; set; }
        public string Otdel { get; set; }
        public string DopInfo { get; set; }
    
        public virtual Predpriyatie Predpriyatie { get; set; }
        public virtual Resume Resume { get; set; }
        public virtual Vakans Vakans { get; set; }
    }
}
