//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LkUgtu.orm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UGTUEntities : DbContext
    {
        public UGTUEntities()
            : base("name=UGTUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Vakans> Vakans { get; set; }
        public virtual DbSet<Predpriyatie> Predpriyatie { get; set; }
        public virtual DbSet<Resume> Resume { get; set; }
        public virtual DbSet<Trudoustr> Trudoustr { get; set; }
    }
}
