//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LkUgtu.orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vakans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vakans()
        {
            this.Resume = new HashSet<Resume>();
            this.Trudoustr = new HashSet<Trudoustr>();
            this.Param_Vakans = new HashSet<Param_Vakans>();
        }
    
        public int idVakans { get; set; }
        public int idPredpr { get; set; }
        public Nullable<int> idGorod { get; set; }
        public int idDolznost { get; set; }
        public int idStatus { get; set; }
        public string DolgnostnObyazan { get; set; }
        public int KolChel { get; set; }
        public string InfoGrafikRab { get; set; }
        public string Lgoty { get; set; }
        public Nullable<bool> LichnoeAvto { get; set; }
        public string DopInfo { get; set; }
        public string VakansName { get; set; }
        public System.DateTime DataPostVakans { get; set; }
        public Nullable<System.DateTime> DataObzvon { get; set; }
        public string TrebKandidat { get; set; }
        public string ZarPlata { get; set; }
        public string OtdelName { get; set; }
    
        public virtual Predpriyatie Predpriyatie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resume> Resume { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trudoustr> Trudoustr { get; set; }
        public virtual Dolznost Dolznost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Param_Vakans> Param_Vakans { get; set; }
        public virtual Status Status { get; set; }
    }
}
